sudo: required

env: ARM_GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2?revision=c34d758a-be0c-476e-a2de-af8c6e16a8a2?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,8-2019-q3-update

language: c
os: linux
compiler:
  - arm-none-eabi-gcc

git:
  depth: false

before_install:
  - echo -e "\n\nmachine github.com\n  $CI_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive
install:
 - sudo apt-get install dfu-util
 - sudo apt-get install python3
 - sudo apt-get install python3-pip
 - sudo pip3 install ecdsa
 - pushd .
 - cd ~
 - mkdir arm-gcc-toolchain
 - wget -O $HOME/arm-gcc-toolchain/gcc.tar.bz2 $ARM_GCC_URL
 - cd arm-gcc-toolchain
 - tar -jxf gcc.tar.bz2 --strip=1
 - popd
 - export PATH=$HOME/arm-gcc-toolchain/bin:$PATH

before_script:
 - git --version
 - python --version
 - echo $0

script:
 - export ROOT_DIT=$(pwd)
 - source $ROOT_DIT/Scripts/gits_travis.sh
 - cd Utils/hex2dfu
 - gcc hex2dfu.c -o hex2dfu
 - cd ../..
 - python3 build.py
 - source $ROOT_DIT/Scripts/generate_bbf.sh
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  api_key: "$marlin_deploy_key"

  file:
    - $MINI_BBF_RELESE_FILE
    - $MINI_BBF_RELESE_FILE_OLD_KEY
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true

notifications:
    email:
      - joshy.mjose@prusa3d.cz
      - robert.pelnar@seznam.cz
